root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - node_modules/
  - dist/
  - .nuxt/
  - .husky/

rules:
  no-unused-vars:
    - 2
    - vars: all
      args: none
  vue/no-v-html: 0
  prettier/prettier:
    - error
    - trailingComma: none
