root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:vue/recommended

parserOptions:
  parser: babel-eslint
  sourceType: module
  allowImportExportEverywhere: true

ignorePatterns:
  - node_modules/
  - dist/
  - .nuxt/

rules:
  no-unused-vars:
    - 2
    - vars: all
      args: none
  vue/no-v-html: 0
